spring:
  application:
    name: error-free-text

  datasource:
    url:
      ${DB_URL:jdbc:postgresql://localhost:5433/error_free_text}
    username: ${DB_USER:error_free_text}
    password: ${DB_PASSWORD:local_password}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public

server:
  port: 8080

speller:
  base-url: https://speller.yandex.net/services/spellservice.json
#  base-url: https://speller.invalid
  connect-timeout: 5s
  read-timeout: 15s

app:
  scheduler:
    fixed-delay-ms: 5000
    batch-size: 10